adding security API actions
opensearch-project/opensearch-ruby pull request #172
Opened 2023-04-27 12:33 UTC by MarrakchiAyoub

### Description
Added API actions for the security plugin

### Issues Resolved
Closes [https://github.com/opensearch-project/opensearch-ruby/issues/171#issue-1683002678].

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-04-28 17:15 UTC, dblock requested changes
Let's start with these.

2023-04-28 17:15 UTC, dblock commented on opensearch-api/lib/opensearch/api/actions/security/change_password.rb
> +# Licensed to OpenSearch B.V. under one or more contributor
There's no such thing as OpenSearch B.V ;) This was an Elastic license grant which is not needed for all new code, remove.

2023-04-28 17:15 UTC, dblock commented on opensearch-api/lib/opensearch/api/actions/security/change_password.rb
> +            username: arguments.delete(:username),
Use `.fetch`. However here we merge `username` from `arguments` back to `arguments` which is a noop.

Can you please check whether we do `delete` all over the place? We should not be modifying hash data coming in. Open an issue if we do and don't have one open. See https://code.dblock.org/2020/11/11/dup-dont-modify-input-hash-parameters-in-ruby.html for an example of how this is a bad idea.

2023-05-15 20:28 UTC, nhtruong commented
Thanks for doing this @MarrakchiAyoub. Would you mind adding the [API specs](https://github.com/opensearch-project/opensearch-ruby/tree/main/opensearch-api/spec/opensearch/api/actions) for these actions as well?

2023-08-16 21:29 UTC, nhtruong commented
This can now be closed since https://github.com/opensearch-project/opensearch-ruby/pull/179 has just been merged.

2023-08-16 21:29 UTC, closed without merging