Add script_score to query DSL
opensearch-project/opensearch-ruby pull request #254
Opened 2024-07-04 06:41 UTC by quangcap

### Description
Script Score query was added to OpenSearch 2.9 and current query DSL does not support it.
This PR add script_score to query DSL.

### Issues Resolved
https://github.com/opensearch-project/opensearch-ruby/issues/253

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-04 08:46 UTC, Earlopain requested changes
Thanks for working on this!. Looks good to me apart from some small nits. Can you also add a changelog entry?

2024-07-04 08:46 UTC, Earlopain commented on lib/opensearch/dsl/search/queries/script_score.rb
> +        #           script source: "_score * params['multiplier']"
This is syntactically incorrect:
```suggestion
        #           script source: "_score * params['multiplier']",
```

2024-07-04 08:46 UTC, Earlopain commented on lib/opensearch/dsl/search/queries/script_score.rb
> +        # A query which wraps another query and returns a customize score for matching documents
```suggestion
        # A query which wraps another query and returns a customized score for matching documents
```

2024-07-06 11:32 UTC, Earlopain approved these changes

2024-07-08 14:26 UTC, dblock approved these changes

2024-07-08 14:26 UTC, dblock commented on lib/opensearch/dsl/search/queries/script_score.rb
> +# Licensed to Elasticsearch B.V. under one or more contributor
No need for an ES header for new files.

2024-07-08 14:26 UTC, dblock requested changes
The ES license part should be removed, please?

2024-07-09 08:27 UTC, quangcap commented
Oh, right! Thanks for guiding me @Earlopain @dblock

2024-07-09 20:28 UTC, dblock approved these changes

2024-07-09 20:28 UTC, merged