Faraday 2 support for opensearch-transport 1
opensearch-project/opensearch-ruby pull request #75
Opened 2022-06-24 20:33 UTC by BrianHawley

- Support Faraday 1.x and 2.x in opensearch-transport.
- Made client autodetection not break if the detected HTTP client is
  there but the associated Faraday adapter is not.
- Made the test setup require the referenced adapters.
- Made it more clear in the README that Faraday uses adapters.
- Backported minoir test fixes from opensearch-transport 2.

[Fixes #59]

### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-06-24 21:01 UTC, BrianHawley commented on opensearch-transport/lib/opensearch/transport/client.rb
> +        adapters = Faraday::Adapter.instance_variable_get(:@registered_middleware) || {}
This is the fastest reliable way to get the adapter collection that works in Faraday 1 and 2. Faraday 2 has a `registered_middleware` method which retrieves the collection, but Faraday 1 only has an undocumented `fetch_middleware` method that retrieves from the middleware. Both define the same instance variable though for the collection.

2022-06-24 21:02 UTC, BrianHawley commented on opensearch-transport/lib/opensearch/transport/client.rb
> +        when defined?(::Patron) && adapters.key?(:patron)
I check the keys with each condition so it will go on to the next case if the adapter isn't defined.

2022-06-28 18:56 UTC, dblock requested changes
This is great! 

I think we need integration tests in CI that use different versions of Faraday to merge this. Care to add?

2022-06-28 18:56 UTC, dblock commented on opensearch-transport/README.md
> +Just include the library's gem and adapter gem, and require the library and adapter in your code, and it will be automatically used.
Nit: I would remove "Just", because nothing is that simple :)

2022-06-28 20:50 UTC, dblock commented
So you're saying we'll end up running faraday 1 and 2 as a side effect? That's ok I suppose, but I think you could do better and add explicit ways to test with a version of Faraday in the test matrix.

2022-06-28 21:07 UTC, BrianHawley commented
I can do a full test unit/test suite for faraday 1 and 2, or maybe just the full opensearch-transport suite, but I can't do a single integration test because the selection of faraday 1 or 2 is done at bundle install time, rather than test runtime. It's better to do all the tests with faraday 1 and 2, just in case.

2022-06-29 21:11 UTC, dblock commented
First, thank you.

Let's move any discussion to #76 because we should be doing all changes on main and then backporting merged changes to 2.x, 1.x, etc., rather than the other way around. So I am going to close this one for now to avoid confusion?

2022-06-29 21:22 UTC, closed without merging

2022-06-29 22:17 UTC, BrianHawley commented
@dblock this PR can be the backport PR once you get around to backporting it, since I already did the work.

2022-06-29 22:21 UTC, dblock commented
We'll figure it out. We actually have label-based automation that does backports and links the two together, and we're not quite done with #76 :) either way don't worry about it for now and thank you.